# Generated by Django 5.2.11 on 2026-02-26 05:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BICommercialComplex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bi_uuid', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='UUID из API')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('city_uuid', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='UUID Города')),
                ('class_name', models.CharField(blank=True, max_length=100, verbose_name='Класс')),
                ('deadline', models.CharField(blank=True, max_length=50, verbose_name='Срок сдачи')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Цена от')),
                ('min_area', models.FloatField(blank=True, null=True, verbose_name='Площадь от')),
                ('max_area', models.FloatField(blank=True, null=True, verbose_name='Площадь до')),
                ('url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True, verbose_name='Фото')),
                ('features', models.JSONField(default=dict, verbose_name='AI Теги')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Коммерческий объект',
                'verbose_name_plural': 'Коммерческие объекты',
                'db_table': 'bi_commercial_complexes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BIComplex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bi_uuid', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='UUID из API')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('city_uuid', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='UUID Города')),
                ('class_name', models.CharField(blank=True, max_length=100, verbose_name='Класс')),
                ('deadline', models.CharField(blank=True, max_length=50, verbose_name='Срок сдачи')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Цена от')),
                ('min_area', models.FloatField(blank=True, null=True, verbose_name='Площадь от')),
                ('max_area', models.FloatField(blank=True, null=True, verbose_name='Площадь до')),
                ('url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True, verbose_name='Фото')),
                ('features', models.JSONField(default=dict, verbose_name='AI Теги')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ЖК (Жилой)',
                'verbose_name_plural': 'ЖК (Жилые)',
                'db_table': 'bi_complexes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BICommercialUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bi_uuid', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='UUID Юнита')),
                ('room_count', models.IntegerField(db_index=True, verbose_name='Помещений')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('max_floor', models.IntegerField(null=True, verbose_name='Всего этажей')),
                ('area', models.FloatField(verbose_name='Площадь')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Базовая цена')),
                ('price_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Цена со скидкой')),
                ('block_name', models.CharField(blank=True, max_length=100, verbose_name='Блок/Секция')),
                ('deadline', models.CharField(blank=True, max_length=50, verbose_name='Срок сдачи секции')),
                ('is_active', models.BooleanField(default=True)),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='Фотографии')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.bicommercialcomplex')),
            ],
            options={
                'verbose_name': 'Офис/Помещение',
                'verbose_name_plural': 'Офисы/Помещения',
                'db_table': 'bi_commercial_units',
            },
        ),
        migrations.CreateModel(
            name='SecondaryProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_uuid', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Внешний UUID')),
                ('external_id', models.BigIntegerField(blank=True, null=True, verbose_name='Внешний ID')),
                ('property_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип объекта')),
                ('deal_type', models.CharField(blank=True, choices=[('sale', 'Продажа'), ('rent', 'Аренда')], max_length=50, null=True, verbose_name='Тип сделки')),
                ('condition', models.CharField(blank=True, max_length=50, null=True, verbose_name='Состояние')),
                ('repair', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ремонт')),
                ('construction_year', models.IntegerField(blank=True, null=True, verbose_name='Год постройки')),
                ('source_url', models.URLField(blank=True, verbose_name='Источник')),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='Фотографии')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена (₸)')),
                ('rooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Количество комнат')),
                ('area', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Площадь (м²)')),
                ('floor', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Этаж')),
                ('total_floors', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Всего этажей')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Район')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('owner_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон владельца')),
                ('owner_name', models.CharField(blank=True, max_length=100, verbose_name='Имя владельца')),
                ('has_parking', models.BooleanField(default=False, verbose_name='Парковка')),
                ('has_balcony', models.BooleanField(default=False, verbose_name='Балкон')),
                ('has_renovation', models.BooleanField(default=False, verbose_name='С ремонтом')),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/%Y/%m/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Проверено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Вторичная недвижимость',
                'verbose_name_plural': 'Вторичная недвижимость',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['city', 'rooms', 'price'], name='properties__city_e46357_idx'), models.Index(fields=['is_active', '-created_at'], name='properties__is_acti_1854c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='BIUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bi_uuid', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='UUID Юнита')),
                ('room_count', models.IntegerField(db_index=True, verbose_name='Комнат')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('max_floor', models.IntegerField(null=True, verbose_name='Всего этажей')),
                ('area', models.FloatField(verbose_name='Площадь')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Базовая цена')),
                ('price_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Цена со скидкой')),
                ('block_name', models.CharField(blank=True, max_length=100, verbose_name='Блок/Секция')),
                ('deadline', models.CharField(blank=True, max_length=50, verbose_name='Срок сдачи секции')),
                ('is_active', models.BooleanField(default=True)),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='Фотографии')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.bicomplex')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'db_table': 'bi_units',
                'indexes': [models.Index(fields=['price_discount', 'room_count'], name='bi_units_price_d_3c0521_idx'), models.Index(fields=['area'], name='bi_units_area_f1eed0_idx')],
            },
        ),
    ]
