# Generated by Django 5.2.11 on 2026-02-26 05:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('web', 'Web')], db_index=True, max_length=20)),
                ('user_id', models.CharField(db_index=True, help_text='Phone for WhatsApp, ID for Telegram, email/uuid for Web', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('total_searches', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('kk', 'Қазақ'), ('en', 'English')], default='ru', max_length=5)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['platform', 'user_id'], name='dashboard_b_platfor_42108b_idx'), models.Index(fields=['last_active_at'], name='dashboard_b_last_ac_464e62_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.TextField(verbose_name='Текст запроса')),
                ('detected_intent', models.CharField(blank=True, max_length=50, verbose_name='Обнаруженное намерение')),
                ('detected_city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('detected_district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Район')),
                ('results_count', models.IntegerField(default=0, verbose_name='Количество результатов')),
                ('search_duration_ms', models.IntegerField(default=0, verbose_name='Время поиска (мс)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to='dashboard.botuser')),
            ],
            options={
                'verbose_name': 'Лог поиска',
                'verbose_name_plural': 'Логи поиска',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('property', 'По объекту'), ('bot', 'По работе бота'), ('search', 'По поиску'), ('other', 'Другое')], max_length=20, verbose_name='Тип')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('property_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID объекта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='dashboard.botuser')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_intent', models.CharField(default='greeting', help_text='Текущее намерение: greeting, search_objects, consult_location и т.д.', max_length=50)),
                ('search_params', models.JSONField(blank=True, default=dict)),
                ('conversation_history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(default='START', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='dashboard.botuser')),
            ],
            options={
                'verbose_name': 'Сессия пользователя',
                'verbose_name_plural': 'Сессии пользователей',
            },
        ),
        migrations.CreateModel(
            name='FavoriteProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(db_index=True, max_length=20)),
                ('object_kind', models.CharField(db_index=True, max_length=20)),
                ('object_id', models.CharField(db_index=True, max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='dashboard.botuser')),
            ],
            options={
                'verbose_name': 'Избранный объект',
                'verbose_name_plural': 'Избранные объекты',
                'constraints': [models.UniqueConstraint(fields=('user', 'object_kind', 'object_id'), name='unique_favorite_object')],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_text', models.TextField(verbose_name='Текст запроса')),
                ('search_params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('contacted', 'Связались'), ('closed', 'Закрыт'), ('cancelled', 'Отменен')], db_index=True, default='new', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(choices=[(0, 'Обычный'), (1, 'Низкий'), (2, 'Средний'), (3, 'Высокий'), (4, 'Срочный'), (5, 'Критический')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='dashboard.botuser')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='dashboard_l_status_06b23d_idx'), models.Index(fields=['-priority', '-created_at'], name='dashboard_l_priorit_47c6fb_idx')],
            },
        ),
    ]
